# Generated by Django 2.2.19 on 2022-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цветовой Hex-код')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальное имя slug')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
