# Generated by Django 2.2.19 on 2022-02-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['slug'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
