# Generated by Django 2.2.19 on 2022-02-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20220204_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-pk'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
