# Generated by Django 2.2.19 on 2022-01-31 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientforrecipe',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ings_for_recipe', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
